/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Recommendation */
        post: operations["create_recommendation_api_v1_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssignmentResponse */
        AssignmentResponse: {
            feature: components["schemas"]["Feature"];
            /** Plan Id */
            plan_id: string;
            status: components["schemas"]["EvaluationStatus"];
        };
        /**
         * BlockReason
         * @description Why one role cannot be assigned a plan.
         *
         *     ``no-candidates`` means the role has no evaluated plans.
         *     ``all-incompatible`` means every evaluated plan for the role is incompatible.
         *     A plan that lacks the role capability is not an evaluated candidate.
         * @enum {string}
         */
        BlockReason: "no-candidates" | "all-incompatible";
        /** BlockedRoleResponse */
        BlockedRoleResponse: {
            feature: components["schemas"]["Feature"];
            reason: components["schemas"]["BlockReason"];
        };
        /**
         * CapabilityKey
         * @description Fixed capability vocabulary. This is not a stored entity.
         * @enum {string}
         */
        CapabilityKey: "static-hosting" | "server-compute" | "serverless-functions" | "database" | "file-storage" | "authentication" | "realtime" | "scheduled-jobs";
        /** CaveatResponse */
        CaveatResponse: {
            /** Plan Id */
            plan_id: string;
            /** Statement */
            statement: string;
            /** Source Id */
            source_id: string;
        };
        /**
         * CheckOutcome
         * @description Whether one need is met, unmet, or not decidable.
         * @enum {string}
         */
        CheckOutcome: "satisfied" | "violated" | "unknown";
        /** CheckResponse */
        CheckResponse: {
            reason_code: components["schemas"]["ReasonCode"];
            outcome: components["schemas"]["CheckOutcome"];
        };
        /** CompositionResponse */
        CompositionResponse: {
            status: components["schemas"]["CompositionStatus"];
            /** Compatible */
            compatible: components["schemas"]["StackResponse"][];
            /** Unknown */
            unknown: components["schemas"]["StackResponse"][];
            /** Incompatible */
            incompatible: components["schemas"]["StackResponse"][];
            /** Blocked Roles */
            blocked_roles: components["schemas"]["BlockedRoleResponse"][];
            /** Combination Count */
            combination_count: number;
            /** Unevaluated Features */
            unevaluated_features: components["schemas"]["Feature"][];
        };
        /**
         * CompositionStatus
         * @description Whether composition produced stacks. This does not rank them.
         * @enum {string}
         */
        CompositionStatus: "composed" | "blocked" | "too-many-combinations" | "no-roles";
        /**
         * ErrorObject
         * @description Stable error code and message. This object has no diagnostic details.
         */
        ErrorObject: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * ErrorResponse
         * @description HTTP body for a recommendation API error.
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorObject"];
        };
        /**
         * EvaluationStatus
         * @description Aggregated check status for one plan in one role.
         *
         *     ``compatible`` means the stated checks are not violated or unknown.
         *     It does not rank plans or choose a winner.
         * @enum {string}
         */
        EvaluationStatus: "compatible" | "unknown" | "incompatible";
        /**
         * ExceedBehavior
         * @description What can happen when included usage is exceeded.
         *
         *     This is a plan-level set, not a per-metric model.
         * @enum {string}
         */
        ExceedBehavior: "charged" | "suspended" | "restricted";
        /**
         * Feature
         * @description A project capability the user asked for.
         *
         *     This is not a catalog ``CapabilityKey``. Some features have no catalog
         *     capability and stay unevaluated.
         * @enum {string}
         */
        Feature: "static-frontend" | "backend-server" | "backend-functions" | "database" | "file-uploads" | "authentication" | "realtime" | "scheduled-jobs" | "ai-api";
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /**
         * LimitMetric
         * @description What a limit measures. The value name includes the base unit.
         * @enum {string}
         */
        LimitMetric: "file-storage-bytes" | "database-size-bytes" | "bandwidth-bytes" | "requests" | "build-seconds";
        /**
         * LimitPeriod
         * @description The window a limit applies to.
         * @enum {string}
         */
        LimitPeriod: "none" | "day" | "month";
        /** LimitResponse */
        LimitResponse: {
            /** Plan Id */
            plan_id: string;
            metric: components["schemas"]["LimitMetric"];
            period: components["schemas"]["LimitPeriod"];
            /** Value */
            value: number | null;
            /** Source Id */
            source_id: string;
        };
        /** PlanBudgetCheckResponse */
        PlanBudgetCheckResponse: {
            reason_code: components["schemas"]["ReasonCode"];
            outcome: components["schemas"]["CheckOutcome"];
            pricing: components["schemas"]["PricingResponse"] | null;
        };
        /** PlanDetailResponse */
        PlanDetailResponse: {
            plan: components["schemas"]["PlanResponse"];
            service: components["schemas"]["ServiceResponse"];
            provider: components["schemas"]["ProviderResponse"];
            pricing: components["schemas"]["PricingResponse"] | null;
            /** Caveats */
            caveats: components["schemas"]["CaveatResponse"][];
            /** Sources */
            sources: components["schemas"]["SourceResponse"][];
        };
        /** PlanEvaluationResponse */
        PlanEvaluationResponse: {
            /** Plan Id */
            plan_id: string;
            role: components["schemas"]["Feature"];
            status: components["schemas"]["EvaluationStatus"];
            capability_check: components["schemas"]["CheckResponse"];
            /** Quantity Checks */
            quantity_checks: components["schemas"]["QuantityCheckResponse"][];
            /** Global Quantity Checks */
            global_quantity_checks: components["schemas"]["QuantityCheckResponse"][];
            budget_check: components["schemas"]["PlanBudgetCheckResponse"] | null;
        };
        /** PlanResponse */
        PlanResponse: {
            /** Id */
            id: string;
            /** Service Id */
            service_id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description: string;
            /** Capabilities */
            capabilities: components["schemas"]["CapabilityKey"][];
        };
        /** PricingResponse */
        PricingResponse: {
            /** Plan Id */
            plan_id: string;
            /** Monthly Base Fee Usd Cents */
            monthly_base_fee_usd_cents: number;
            /** Exceed Behaviors */
            exceed_behaviors: components["schemas"]["ExceedBehavior"][];
            /** Source Id */
            source_id: string;
        };
        /** ProviderResponse */
        ProviderResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description: string;
        };
        /** QuantityCheckResponse */
        QuantityCheckResponse: {
            reason_code: components["schemas"]["ReasonCode"];
            outcome: components["schemas"]["CheckOutcome"];
            limit: components["schemas"]["LimitResponse"] | null;
            /** Other Period Limits */
            other_period_limits: components["schemas"]["LimitResponse"][];
        };
        /**
         * ReasonCode
         * @description Why a single need check ended the way it did.
         * @enum {string}
         */
        ReasonCode: "capability-provided" | "capability-not-provided" | "within-limit" | "unlimited" | "exceeds-limit" | "limit-not-found" | "limit-period-mismatch" | "within-budget" | "over-budget" | "pricing-not-found";
        /**
         * RecommendationRequest
         * @description JSON body for one stack composition request.
         */
        RecommendationRequest: {
            /** Features */
            features: components["schemas"]["Feature"][];
            /** File Storage Bytes */
            file_storage_bytes?: number | null;
            /** Database Size Bytes */
            database_size_bytes?: number | null;
            /** Monthly Bandwidth Bytes */
            monthly_bandwidth_bytes?: number | null;
            /** Monthly Budget Usd Cents */
            monthly_budget_usd_cents?: number | null;
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            requirement: components["schemas"]["RequirementResponse"];
            /** Roles */
            roles: components["schemas"]["RoleEvaluationResponse"][];
            composition: components["schemas"]["CompositionResponse"];
            /** Unevaluated Features */
            unevaluated_features: components["schemas"]["Feature"][];
            /** Plans */
            plans: {
                [key: string]: components["schemas"]["PlanDetailResponse"];
            };
            /** Sources */
            sources: {
                [key: string]: components["schemas"]["SourceResponse"];
            };
        };
        /** RequirementResponse */
        RequirementResponse: {
            /** Features */
            features: components["schemas"]["Feature"][];
            /** File Storage Bytes */
            file_storage_bytes: number | null;
            /** Database Size Bytes */
            database_size_bytes: number | null;
            /** Monthly Bandwidth Bytes */
            monthly_bandwidth_bytes: number | null;
            /** Monthly Budget Usd Cents */
            monthly_budget_usd_cents: number | null;
        };
        /** RoleEvaluationResponse */
        RoleEvaluationResponse: {
            role: components["schemas"]["Feature"];
            /** Compatible */
            compatible: components["schemas"]["PlanEvaluationResponse"][];
            /** Unknown */
            unknown: components["schemas"]["PlanEvaluationResponse"][];
            /** Incompatible */
            incompatible: components["schemas"]["PlanEvaluationResponse"][];
        };
        /** ServiceResponse */
        ServiceResponse: {
            /** Id */
            id: string;
            /** Provider Id */
            provider_id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description: string;
        };
        /** SourceResponse */
        SourceResponse: {
            /** Id */
            id: string;
            /** Url */
            url: string;
            /**
             * Checked At
             * Format: date
             */
            checked_at: string;
            /** Notes */
            notes: string;
        };
        /** StackBudgetCheckResponse */
        StackBudgetCheckResponse: {
            /** Budget Usd Cents */
            budget_usd_cents: number;
            /** Priced Plan Ids */
            priced_plan_ids: string[];
            /** Unpriced Plan Ids */
            unpriced_plan_ids: string[];
            /** Known Total Usd Cents */
            known_total_usd_cents: number;
            reason: components["schemas"]["ReasonCode"];
            outcome: components["schemas"]["CheckOutcome"];
        };
        /** StackResponse */
        StackResponse: {
            /** Key */
            key: string;
            /** Assignments */
            assignments: components["schemas"]["AssignmentResponse"][];
            /** Plan Ids */
            plan_ids: string[];
            status: components["schemas"]["EvaluationStatus"];
            budget_check: components["schemas"]["StackBudgetCheckResponse"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_recommendation_api_v1_recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description The request is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An internal error occurred. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const blockReasonValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["BlockReason"]> = ["no-candidates", "all-incompatible"];
export const capabilityKeyValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CapabilityKey"]> = ["static-hosting", "server-compute", "serverless-functions", "database", "file-storage", "authentication", "realtime", "scheduled-jobs"];
export const checkOutcomeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CheckOutcome"]> = ["satisfied", "violated", "unknown"];
export const compositionStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CompositionStatus"]> = ["composed", "blocked", "too-many-combinations", "no-roles"];
export const evaluationStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["EvaluationStatus"]> = ["compatible", "unknown", "incompatible"];
export const exceedBehaviorValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ExceedBehavior"]> = ["charged", "suspended", "restricted"];
export const featureValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Feature"]> = ["static-frontend", "backend-server", "backend-functions", "database", "file-uploads", "authentication", "realtime", "scheduled-jobs", "ai-api"];
export const limitMetricValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["LimitMetric"]> = ["file-storage-bytes", "database-size-bytes", "bandwidth-bytes", "requests", "build-seconds"];
export const limitPeriodValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["LimitPeriod"]> = ["none", "day", "month"];
export const reasonCodeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ReasonCode"]> = ["capability-provided", "capability-not-provided", "within-limit", "unlimited", "exceeds-limit", "limit-not-found", "limit-period-mismatch", "within-budget", "over-budget", "pricing-not-found"];
