export const KNOWN_CAVEAT_KOREAN: Record<string, string> = {
  'The Free plan includes 500 builds per month.': '월 500회 빌드 제한',
  'The Free plan allows one build at a time.': '동시 빌드 1개 제한',
  'Builds time out after 20 minutes.': '빌드 타임아웃 20분',
  'A Free plan site can contain up to 20,000 files.': '사이트당 최대 20,000개 파일',
  'A single Pages asset can be at most 25 MiB.': '단일 에셋 최대 25MB',
  'Requests to Pages Functions count toward the Workers plan quota.': 'Pages 함수 호출은 Workers 쿼터와 공유',
  'The free tier includes 1 million Class A operations per month.': '월 100만 회 Class A 오퍼레이션 무료',
  'The free tier includes 10 million Class B operations per month.': '월 1,000만 회 Class B 오퍼레이션 무료',
  'The free tier applies only to Standard storage, and usage beyond the included amount is billed.': '초과 사용 시 종량제 과금 주의',
  'Each workspace receives 750 Free instance hours per calendar month.': '워크스페이스당 월 750시간 무료 인스턴스',
  'When Free instance hours are exhausted, Free web services are suspended until the next month.': '무료 시간 소진 시 다음 달까지 서비스 일시 정지',
  'A Free web service spins down after 15 minutes without inbound traffic.': '15분 미요청 시 슬립(Spin down)',
  'Spinning a Free web service back up takes about one minute.': '슬립 후 첫 요청 시 재기동(Cold Start) 약 1분 소요',
  'Free web services have an ephemeral filesystem.': '임시 파일시스템 (재시작 시 저장 데이터 초기화)',
  'A persistent disk cannot be attached to a Free web service.': '영구 디스크 연결 불가',
  'A Free web service cannot scale beyond a single instance.': '단일 인스턴스로만 실행 가능',
  'Render may restart a Free web service at any time.': '인스턴스가 임의로 재시작될 수 있음',
  'Render says not to use Free instances for production applications.': '프로덕션 운영용으로는 권장되지 않음',
  'The Free web service compute plan provides 0.1 CPU.': '무료 컴퓨팅 0.1 CPU',
  'The Free web service compute plan provides 512 MB of RAM.': '무료 메모리 512MB RAM',
  'The Free plan includes two projects.': '무료 활성 프로젝트 최대 2개',
  'The 500 MB database size quota applies per project.': '프로젝트당 500MB DB 용량 제한',
  'The 1 GB storage quota applies per organization.': '조직당 1GB 파일 스토리지 제한',
  'The 5 GB egress quota applies per organization.': '조직당 5GB 아웃바운드 트래픽 제한',
  'The Free plan includes 50,000 monthly active users.': '월 50,000 MAU 무료 인증 지원',
  'The Free plan includes 500,000 Edge Function invocations.': '월 50만 회 Edge Functions 호출',
  'The Free plan includes 2,000,000 Realtime messages.': '월 200만 건 실시간 메시지 포함',
  'The Free plan includes 200 Realtime peak connections.': '최대 200개 동시 실시간 연결',
}
